CREATE TABLE DATASOURCECONFIG (
	id IDENTITY PRIMARY KEY,
	driverclassname VARCHAR(255),
	url VARCHAR(255),
	name VARCHAR(255),
	username VARCHAR(255),
	password VARCHAR(255),
	initialize BOOLEAN
);

CREATE TABLE ESTOQUE (
	id IDENTITY PRIMARY KEY,
	produto VARCHAR(255),
	valor VARCHAR(255),
	quantidade INTEGER,
	data_cadastro DATE
);